import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";
import { loadSchemas, schemaRoot, type Schema } from "../src/index.js";

type Json = unknown;

const BASE = "galatea:/";

function pascal(id: string): string {
  return id
    .replace(/\.json$/, "")
    .split(/[/._-]+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
}

function pointer(doc: Json, ptr: string): Json {
  let node = doc;
  for (const raw of ptr.split("/").slice(1)) {
    const part = decodeURIComponent(raw).replace(/~1/g, "/").replace(/~0/g, "~");
    node = (node as Record<string, Json>)[part];
    if (node === undefined) throw new Error(`no ${ptr}`);
  }
  return node;
}

/** A copy of `node` with every $ref replaced by what it points at, recursively; titles dropped. */
function inline(node: Json, baseId: string, byId: Map<string, Schema>): Json {
  if (Array.isArray(node)) return node.map((n) => inline(n, baseId, byId));
  if (node === null || typeof node !== "object") return node;
  const obj = node as Record<string, Json>;
  if (typeof obj.$ref === "string") {
    const url = new URL(obj.$ref, BASE + baseId);
    const id = url.pathname.slice(1);
    const doc = byId.get(id);
    if (!doc) throw new Error(`${baseId}: unresolved $ref ${obj.$ref}`);
    const { $ref: _ref, ...rest } = obj;
    const target = inline(pointer(doc, url.hash.slice(1)), id, byId) as Record<string, Json>;
    const siblings = inline(rest, baseId, byId) as Record<string, Json>;
    return Object.keys(siblings).length ? { allOf: [target], ...siblings } : target;
  }
  const out: Record<string, Json> = {};
  for (const [k, v] of Object.entries(obj)) {
    if (k === "title" || k === "$defs" || k === "$id" || k === "$schema") continue;
    out[k] = inline(v, baseId, byId);
  }
  return out;
}

/** Writes one .ts per schema under outDir, and an index.ts; returns the relative paths. */
export async function generateTypes(outDir: string): Promise<string[]> {
  const schemas = loadSchemas();
  const byId = new Map(schemas.map((s) => [s.$id, s]));
  const written: string[] = [];
  const names: [string, string][] = [];
  for (const schema of schemas) {
    if (schema.$id === "common.json" || schema.$id === "galatea-bridge.schema.json") continue;
    const name = pascal(schema.$id);
    const flat = inline(schema, schema.$id, byId) as Record<string, Json>;
    const ts = await compile(flat as never, name, {
      bannerComment: `/* Generated from conformance/schemas/${schema.$id} by scripts/gen-types.ts. Do not edit. */`,
      additionalProperties: true,
      declareExternallyReferenced: false,
      format: true,
      strictIndexSignatures: true,
    });
    const rel = schema.$id.replace(/\.json$/, ".ts");
    mkdirSync(dirname(join(outDir, rel)), { recursive: true });
    writeFileSync(join(outDir, rel), ts);
    written.push(rel);
    names.push([name, rel]);
  }
  const index = names
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([name, rel]) => `export type { ${name} } from "./${rel.replace(/\.ts$/, ".js")}";`)
    .join("\n");
  writeFileSync(join(outDir, "index.ts"), `/* Generated by scripts/gen-types.ts. Do not edit. */\n${index}\n`);
  written.push("index.ts");
  return written;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const out = join(schemaRoot, "src", "generated");
  const written = await generateTypes(out);
  console.log(`wrote ${written.length} files to ${out}`);
}
